version: '3'
services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: gorm
      POSTGRES_PASSWORD: gorm
    ports:
      - "9920:5432"

  mongo:
    image: mongo:8.0-rc
    ports:
      - "9921:27017"